<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Diary.Application\Diary.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="Concentus" />
  </ItemGroup>
</Project>
